### ISSUE TITLE
[Can you provide some sample of train.txt]

### ISSUE THREAD

**Issue by Vietdung113** [MrBananaHuman/KoGPT2ForPara#1]
Thanks for your sharing.
Can you put some sample of train.txt file ?

**Comment by MrBananaHuman** [comment]
Hello! :-)

You can download the dataset from [1](https://github.com/warnikchow/paraKQC) and [2](https://github.com/songys/Question_pair)
with preprocessing codes (make_sentence_pair.py and make_train_data.py)
The training data consists of two columns, [source, target].
